version: '3.7'
services:

  cargo:
    image: harrisonai/rust:1.56-0.2
    entrypoint: cargo
    volumes:
      - '~/.cargo/registry:/usr/local/cargo/registry'
      - '.:/app'
    working_dir: '/app'

  terraform:
    image: hashicorp/terraform:1.0.4
    volumes:
      - '.:/app'
      - '$HOME/.aws:$HOME/.aws:ro'
    environment:
      HOME: "${HOME}"
    working_dir: '/app'

  envvars:
    image: 'flemay/envvars'
    env_file: .env
    working_dir: '/app'
    volumes:
      - '.:/app'

